variable "cloudflare_email" {}
variable "cloudflare_r2_account_id" {}
variable "hcloud_api_token" {}
variable "juicefs_kdrive_accesskey" {}
variable "juicefs_kdrive_bucket" {}
variable "juicefs_kdrive_secretkey" {}
variable "objectstorage_access_key_id" {}
variable "objectstorage_access_key_secret" {}
variable "objectstorage_bucket" {}
variable "objectstorage_endpoint" {}
variable "tfe_token" {}